/*
 * CSE 572 Winter 2019 Group 6
 * Iron River Animal Hospital
 */

INSERT INTO LIKES VALUES(1, 2);
INSERT INTO LIKES VALUES(2, 100);
INSERT INTO LIKES VALUES(3, 21;
INSERT INTO LIKES VALUES(4, 33);
INSERT INTO LIKES VALUES(5, 3);
