/*
 * CSE 572 Winter 2019 Group 6
 * Iron River Animal Hospital
 */

INSERT INTO LIKES VALUES(1, 2);
INSERT INTO LIKES VALUES(2, 9);
INSERT INTO LIKES VALUES(1, 3);
INSERT INTO LIKES VALUES(3, 1);
INSERT INTO LIKES VALUES(4, 7);
INSERT INTO LIKES VALUES(5, 3);
