/*
 * CSE 572 Winter 2019 Group 6
 * Iron River Animal Hospital
 */

-- View; pets that have not been chipped yet

CREATE OR REPLACE VIEW UNCHIPPED_PETS AS
SELECT P.NAME, O.FIRST_NAME, O.LAST_NAME, O.PHONE_NUMBER
FROM MEDICAL_HISTORY MH
JOIN PETS P ON P.ID = MH.PET_ID
JOIN OWNERS O ON O.ID = P.OWNER_ID
WHERE MH.CHIPPED = 0;