/*
 * CSE 572 Winter 2019 Group 6
 * Iron River Animal Hospital
 */

-- View; payments that need to be paid

CREATE OR REPLACE VIEW UNPAID_INVOICES AS
SELECT P.ID, O.FIRST_NAME, O.LAST_NAME, P.AMOUNT_DUE, P.AMOUNT_PAID
FROM PAYMENTS P
JOIN PAYMENT_METHODS PM ON PM.ID = P.PAYMENT_METHOD_ID
JOIN OWNERS O ON O.ID = PM.OWNER_ID
WHERE AMOUNT_PAID < AMOUNT_DUE;