/*
 * CSE 572 Winter 2019 Group 6
 * Iron River Animal Hospital
 */

-- create tables, sequences, and triggers

@CREATE/CREATE_TYPE.sql
@CREATE/CREATE_DRUGS.sql
@CREATE/CREATE_JOBS.sql
@CREATE/CREATE_INSURANCE.sql
@CREATE/CREATE_STAFF.sql
@CREATE/CREATE_OWNERS.sql
@CREATE/CREATE_PAYMENT_METHODS.sql
@CREATE/CREATE_PETS.sql
@CREATE/CREATE_PAYMENTS.sql
@CREATE/CREATE_MEDICAL_HISTORY.sql
@CREATE/CREATE_APPOINTMENTS.sql
@CREATE/CREATE_USERS.sql
@CREATE/CREATE_POSTS.sql
@CREATE/CREATE_FEEDBACK.sql
@CREATE/CREATE_VETERINARIAN_INFO.sql
@CREATE/CREATE_LIKES.sql
@CREATE/CREATE_COMMENTS.sql
@CREATE/TRIGGER_PETS.sql
@CREATE/TRIGGER_STAFF.sql