/*
 * CSE 572 Winter 2019 Group 6
 * Iron River Animal Hospital
 */

-- drop tables (and triggers) and sequences

DROP TABLE APPOINTMENTS;
DROP TABLE MEDICAL_HISTORY;
DROP TABLE PAYMENTS;
DROP TABLE PETS;
DROP TABLE PAYMENT_METHODS;
DROP TABLE OWNERS;
DROP TABLE STAFF;
DROP TABLE INSURANCE;
DROP TABLE JOBS;
DROP TABLE DRUGS;
DROP TABLE TYPE;
DROP TABLE COMMENTS;
DROP TABLE LIKES;
DROP TABLE VETERINARIAN_INFO;
DROP TABLE FEEDBACK;
DROP TABLE POSTS;
DROP TABLE USERS;
DROP SEQUENCE appointments_id;
DROP SEQUENCE comments_id;
DROP SEQUENCE drugs_id;
DROP SEQUENCE insurance_id;
DROP SEQUENCE jobs_id;
DROP SEQUENCE medical_history_id;
DROP SEQUENCE owners_id;
DROP SEQUENCE payments_id;
DROP SEQUENCE payment_methods_id;
DROP SEQUENCE pets_id;
DROP SEQUENCE posts_id;
DROP SEQUENCE staff_id;
DROP SEQUENCE type_id;
DROP SEQUENCE users_id;