/*
 * CSE 572 Winter 2019 Group 6
 * Iron River Animal Hospital
 */

-- inserts sample data into tables

@INSERT/INSERT_TYPE.sql
@INSERT/INSERT_DRUGS.sql
@INSERT/INSERT_JOBS.sql
@INSERT/INSERT_INSURANCE.sql
@INSERT/INSERT_STAFF.sql
@INSERT/INSERT_OWNERS.sql
@INSERT/INSERT_PAYMENT_METHODS.sql
@INSERT/INSERT_PETS.sql
@INSERT/INSERT_PAYMENTS.sql
@INSERT/INSERT_MEDICAL_HISTORY.sql
@INSERT/INSERT_APPOINTMENTS.sql
@INSERT/INSERT_USERS.sql
@INSERT/INSERT_POSTS.sql
@INSERT/INSERT_FEEDBACK.sql
@INSERT/INSERT_VETERINARIAN_INFO.sql
@INSERT/INSERT_LIKES.sql
@INSERT/INSERT_COMMENTS.sql